### PR TITLE
package.json

### PR DESCRIPTION
**Pull request by robertlove**
Changes proposed in this pull request:

- Add package.json file
- Propose standard for minimum required fields for all Q-CTRL package.json files
- Propose standard for the values of those fields
- See https://github.com/qctrl/template/blob/master/pyproject.toml for the python example

### CODE REVIEW

**Review by daimz — APPROVED** [review]
Looks good, once published. I'll modify Elements and Elements-CSS as needed.

**Comment by robertlove** [comment]
@cfarrend this doesn't cover using DESCRIPTION.md for the package home page content. I can't see anything in the docs to do this. As far as I can tell, they'll always use the README file. If this is the case, maybe a workaround is to have a blanket rule across all repos that says, when a package is released, if a DESCRIPTION file exists, create or update a README file with the contents of DESCRIPTION. WDYT?

**Review by robo2323 — APPROVED** [review]
LGTM! Will update relevant repos...

**Review by tysonwolker — APPROVED** [review]

**Comment by cfarrend** [comment]
> @cfarrend this doesn't cover using DESCRIPTION.md for the package home page content. I can't see anything in the docs to do this. As far as I can tell, they'll always use the README file. If this is the case, maybe a workaround is to have a blanket rule across all repos that says, when a package is released, if a DESCRIPTION file exists, create or update a README file with the contents of DESCRIPTION. WDYT?

I did a bit of digging around and came across this here: https://stackoverflow.com/questions/41297117/how-to-specify-different-readme-files-for-github-and-npm

I just need to test myself, but someone believes having a file called `README` will take precedence over `README.md`. Another person included a script to move README files around which looks like a bit of a hack, just seems to be renaming the README files before publishing which will work. Considering we have a build command specifically targeted towards NPM publishing it can probably be put in there. 

So it could be simple by having a correctly named file (though I'm not sure if this is actually the case), or we need to change some of the publishing scripts. Other people also used a specific `.github/README.md` file which shows up on the front page only when using GitHub and that way the customer facing README can remain in its original spot. Anyway, it can be done, just depends on how hard to implement.

**Review by cfarrend — APPROVED** [review]
LGTM

I was trying to find some parts to change, but it all seems pretty standard to me. 

One thing that is unfortunate is that for private packages there is really no way of getting them to go to GitHub. `repository` is reserved for public URLs and they specifically state to not put in a project page (e.g github.com/qctrl). Maybe we want to look at making our public facing READMEs more official with logos, badges, links, etc that links to our socials.

Something that may be missing is where the other fields that we use go (e.g `scripts`). I assume just like `pyproject.toml`, these fields will go in according to the order listed out on https://docs.npmjs.com/configuring-npm/package-json.

**Pull request merged**
